/** Escape HTML special characters to prevent XSS from database content */
function escapeHtml(str) {
  if (str === null || str === undefined) return '';
  return String(str).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
}

/**
 * provider/main.js — Provider Dashboard Logic
 *
 * Shows all patients the provider has access to.
 * Providers gain access by entering an 8-character code generated by a parent.
 *
 * Paginated: renders PAGE_SIZE items at a time with a "Show More" button.
 */

const PAGE_SIZE = 25;
let allPatients = [];
let visibleCount = 0;

async function activateCode() {
  const code    = document.getElementById('access-code-input').value.trim().toUpperCase();
  const errEl   = document.getElementById('code-error');
  const succEl  = document.getElementById('code-success');
  errEl.classList.add('hidden');
  succEl.classList.add('hidden');

  if (!code || code.length !== 8) {
    errEl.textContent = 'Please enter the full 8-character access code';
    errEl.classList.remove('hidden');
    return;
  }

  try {
    const result = await window.electronAPI.activateAccessCode(code);

    if (result.success) {
      succEl.classList.remove('hidden');
      document.getElementById('access-code-input').value = '';
      // Reload the patient list to show the new patient
      await loadPatients();
    } else {
      errEl.textContent = result.error || 'Invalid or expired access code';
      errEl.classList.remove('hidden');
    }
  } catch (err) {
    console.error('Failed to activate access code:', err);
    errEl.textContent = 'Something went wrong. Please try again.';
    errEl.classList.remove('hidden');
  }
}

/** Render a single patient item and append it to the container */
function renderPatient(p, container) {
  const item = document.createElement('div');
  item.className = 'patient-list-item';
  item.setAttribute('role', 'button');
  item.setAttribute('tabindex', '0');
  item.addEventListener('click', () => window.electronAPI.navigate('provider-patient-view', { childId: p.child_id }));

  // Create avatar initials from the child's name
  const initials = (p.child_name || 'P').split(' ').map(w => w[0]).join('').substring(0, 2).toUpperCase();
  const today    = new Date();
  const bday     = new Date(p.birthday);
  const age      = Math.floor((today - bday) / (365.25 * 24 * 60 * 60 * 1000));

  item.setAttribute('aria-label', `${p.child_name}, age ${age}, parent ${p.parent_username}. Click to view patient details.`);

  // Allow keyboard activation (Enter/Space)
  item.addEventListener('keydown', (e) => {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      window.electronAPI.navigate('provider-patient-view', { childId: p.child_id });
    }
  });

  item.innerHTML = `
    <div class="patient-avatar">${initials}</div>
    <div class="patient-info" style="flex:1">
      <div class="patient-name">${escapeHtml(p.child_name)}</div>
      <div class="patient-meta">Age ${age} · Parent: ${escapeHtml(p.parent_username)}</div>
    </div>
    <span style="color:var(--color-text-secondary);font-size:1.25rem">›</span>
  `;
  container.appendChild(item);
}

/** Render the next batch of patients */
function showMore() {
  const container = document.getElementById('patient-list');
  const end = Math.min(visibleCount + PAGE_SIZE, allPatients.length);

  for (let i = visibleCount; i < end; i++) {
    renderPatient(allPatients[i], container);
  }
  visibleCount = end;
  updatePaginationControls();
}

/** Update the counter and Show More button visibility */
function updatePaginationControls() {
  const controls = document.getElementById('pagination-controls');
  if (!controls) return;

  const counter = document.getElementById('pagination-counter');
  const btn     = document.getElementById('show-more-btn');

  counter.textContent = `Showing ${visibleCount} of ${allPatients.length}`;
  btn.classList.toggle('hidden', visibleCount >= allPatients.length);
  controls.classList.remove('hidden');
}

async function loadPatients() {
  try {
    allPatients = await window.electronAPI.getProviderPatients();
    const container  = document.getElementById('patient-list');

    if (allPatients.length === 0) {
      container.innerHTML = `
        <div class="empty-state">
          <div class="empty-icon">👨‍⚕️</div>
          <p>No patients yet</p>
          <p class="text-muted" style="font-size:var(--font-size-sm);margin-top:8px">
            Enter an access code above to add your first patient.
          </p>
        </div>
      `;
      return;
    }

    container.innerHTML = '';
    visibleCount = 0;
    showMore();
  } catch (err) {
    console.error('Failed to load patients:', err);
    const container = document.getElementById('patient-list');
    container.innerHTML = `
      <div class="empty-state">
        <div class="empty-icon">⚠️</div>
        <p>Could not load patients</p>
        <p class="text-muted" style="font-size:var(--font-size-sm);margin-top:8px">
          Please try refreshing the page.
        </p>
      </div>
    `;
  }
}

async function initializePage() {
  try {
    const session = await window.electronAPI.getSession();
    if (!session || !session.userId) { window.electronAPI.navigate('landing'); return; }

    document.getElementById('username-display').textContent = 'Dr. ' + session.username;
    await loadPatients();
  } catch (err) {
    console.error('Failed to initialize provider dashboard:', err);
    document.getElementById('username-display').textContent = 'Error loading page';
  }
}
document.addEventListener('DOMContentLoaded', () => {
  initializePage();
  document.getElementById('logout-btn').addEventListener('click', () => window.electronAPI.logout());
  document.getElementById('activate-code-btn').addEventListener('click', activateCode);
  document.getElementById('nav-settings').addEventListener('click', () => window.electronAPI.navigate('settings'));
  document.getElementById('show-more-btn').addEventListener('click', showMore);
});
